Merge Chrultrabook #102 PR into vuepress rebase
ethanaobrien/docz pull request #7
Opened 2023-11-12 17:02 UTC by CoolPenguin27

This pr merges what I did in this [pr](https://github.com/chrultrabook/docs/pull/102) into here. This also restores the original LICENSE and README files and moves the chrultrabook controller ad into post-install.md

2023-11-12 18:38 UTC, ethanaobrien requested changes

2023-11-12 18:38 UTC, ethanaobrien commented on src/docs/recovery-mode.md
> +<img src="https://kmpic.asus.com/images/2022/11/17/6bec2799-6ad7-43d5-82a3-f57bfeb795b6.png" width=500x500>
Can we download any external images and add them to the images directory, similar to how the coolstar paid driver pages are done

2023-11-12 18:38 UTC, ethanaobrien commented on src/docs/developer-mode.md
> +<table>
Can we convert this table to markdown?

2023-11-12 20:47 UTC, CoolPenguin27 commented on src/docs/developer-mode.md
> +<table>
I dont know.

2023-11-12 20:49 UTC, ethanaobrien commented on src/docs/developer-mode.md
> +<table>
I'll do this later then, don't worry about it

2023-11-12 20:57 UTC, CoolPenguin27 commented on src/docs/recovery-mode.md
> +<img src="https://kmpic.asus.com/images/2022/11/17/6bec2799-6ad7-43d5-82a3-f57bfeb795b6.png" width=500x500>
we also need to update the links of the current images so that they dont break

2023-11-13 06:08 UTC, CoolPenguin27 commented on src/docs/recovery-mode.md
> +<img src="https://kmpic.asus.com/images/2022/11/17/6bec2799-6ad7-43d5-82a3-f57bfeb795b6.png" width=500x500>
probably when the vuepress rebase pr is about to be merged

2023-11-13 16:47 UTC, merged